client_id = "edc2ea8f83118b6f34be6dda9229bb32"
name = "ECOM HOUSE Audit Tool"
application_url = "https://eh-full-audit.vercel.app/"
embedded = true

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://eh-full-audit.vercel.app/auth/callback"
]

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://eh-full-audit.vercel.app/api/webhooks/customers-data-request"
  customer_deletion_url = "https://eh-full-audit.vercel.app/api/webhooks/customers-redact"
  shop_deletion_url = "https://eh-full-audit.vercel.app/api/webhooks/shop-redact"

[pos]
embedded = false

[build]
include_config_on_deploy = true
