'use client';
import { useState } from 'react';

const ITEMS = [
  { q: 'How long does the audit take?', a: 'Most audits are delivered within 2 hours of connecting your accounts. Larger stores can take up to 24 hours.' },
  { q: 'What data do you access?', a: 'Read-only access to Shopify products, orders, and customers (last 60 days), and read-only access to your Meta Ads campaigns, ads, and insights (last 30 days). We never modify anything in your accounts.' },
  { q: 'Do I need to install anything in Shopify?', a: 'You authenticate via standard Shopify OAuth — no custom app to install in your store. We never write data back.' },
  { q: 'What does the audit include?', a: 'A 5-page AI-powered report with an overall A–F health score, four category breakdowns (Store Performance, Ad Creative Health, Funnel Optimization, Retention Strategy), and a top-5 prioritized action list with expected impact.' },
  { q: 'Is the audit specific to my business or generic?', a: 'Specific. Findings reference your real product names, campaign names, and spend amounts — generated by Claude analyzing your actual data.' },
  { q: 'What happens after the audit?', a: 'You can implement the recommendations yourself, or book a free strategy call with the ECOM HOUSE team to discuss execution.' },
];

export default function Faq() {
  const [open, setOpen] = useState<number | null>(0);
  return (
    <div className="space-y-3">
      {ITEMS.map((it, i) => {
        const isOpen = open === i;
        return (
          <div key={i} className="bg-card border border-border rounded-xl overflow-hidden">
            <button
              onClick={() => setOpen(isOpen ? null : i)}
              className="w-full text-left px-5 py-4 flex items-center justify-between gap-4 hover:bg-card-hover transition-colors"
            >
              <span className="font-semibold text-sm sm:text-base">{it.q}</span>
              <span className={`text-gold text-xl transition-transform ${isOpen ? 'rotate-45' : ''}`}>+</span>
            </button>
            {isOpen && (
              <div className="px-5 pb-5 pt-0 text-sm text-muted-strong leading-relaxed border-t border-border">
                <div className="pt-4">{it.a}</div>
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}
